# Generated by Django 5.0.3 on 2024-04-03 11:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_approved", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Approved"),
                            ("P", "Pending"),
                            ("D", "Draft"),
                            ("R", "Rejected"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "group_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_project",
                        to="group.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Project",
                "verbose_name_plural": "Group Projects",
                "db_table": "group_project",
                "ordering": ["-created_at"],
            },
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
    ]
