# Generated by Django 5.0.6 on 2024-05-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupproject',
            old_name='group_project',
            new_name='group',
        ),
    ]
