# Generated by Django 5.0.3 on 2024-03-27 10:24

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('max_grup_size', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='course.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='semester.semester')),
            ],
            options={
                'verbose_name': 'Semester Course',
                'verbose_name_plural': 'Semester Courses',
                'db_table': 'semester_course',
                'ordering': ['-created_at'],
                'unique_together': {('semester', 'course')},
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
