# Generated by Django 5.0.3 on 2024-03-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semestercourse',
            unique_together=set(),
        ),
    ]
