# Generated by Django 5.0.3 on 2024-04-03 11:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group_project", "0001_initial"),
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="data")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_submitted", models.BooleanField(default=False)),
                ("version", models.IntegerField(blank=True, null=True)),
                (
                    "plagiarism_file",
                    models.FileField(blank=True, null=True, upload_to="data"),
                ),
                ("plagiarism_rate", models.IntegerField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group_project.groupproject",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.report"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Report",
                "verbose_name_plural": "Project Reports",
                "db_table": "project_report",
                "ordering": ["-created_at"],
            },
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
    ]
