# Generated by Django 5.0.6 on 2024-05-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group Member', 'verbose_name_plural': 'Group Members'},
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
