# Generated by Django 5.0.3 on 2024-04-03 10:43

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicianGroupGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('mid_term', models.IntegerField(blank=0)),
                ('final', models.IntegerField(blank=True, null=True)),
                ('make_up', models.IntegerField(blank=True, null=True)),
                ('academician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academician_group_grade', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academician_group_grade', to='group.group')),
            ],
            options={
                'verbose_name': 'Academician Group Grade',
                'verbose_name_plural': 'Academician Group Grades',
                'db_table': 'academician_group_grade',
                'ordering': ['-created_at'],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
